print('Проверяем утверждение apple > fanat:', 'apple' > 'fanat')
print('Проверяем утверждение abracadabra > Tarantino:', 'abracadabra' > 'Tarantino')
print('Проверяем утверждение yahoo > yandex:', 'yahoo' > 'yandex')
print('Проверяем утверждение gool > logo:', 'gool' > 'logo')
print('Сформируем пары с наибольшими словами fanat > abracadabra:', 'fanat' > 'abracadabra')
print('Сформируем пары с наибольшими словами yandex > logo:', 'yandex' > 'logo')
print('Последняя пара состоит из самых больших слов fanat > yandex:', 'fanat' > 'yandex')
